# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

 
- bash: |

 
curl 'https://releases.hashicorp.com/terraform/0.12.25/terraform_0.12.25_linux_amd64.zip' --output terraform_0.12.25.zip

 
unzip terraform_0.12.25.zip

 
mv terraform terraform_0.12.25

 
 

 
#echo "credentials \"terraform.automation.agl.com.au\" {token = \"$terraform_token\"}" > ~/.terraformrc

 
./terraform_0.12.25 init && ./terraform_0.12.25 plan && ./terraform_0.12.25 apply

 
workingDirectory: 'master'

 
displayName: 'demotf'

 
#env:

 
#terraform_token: $(tcs-cloudops-terraform-team-token)

 
 

 
trigger: none

 
pr: none
